### ISSUE TITLE
Uploading docker app fails if tornado version is 4.0

### ISSUE THREAD

**Issue by burkostya** [cocaine/cocaine-tools#12]
On fresh installation of cocaine-tools with `pip install cocaine-tools` next command fails

```bash
cocaine-tool app upload --name flask --docker=unix:///var/run/docker.sock --registry=docker.registry:5000 --manifest manifest.json --timeout 200000 --debug tools
```

with error `FAIL - __init__() takes exactly 9 arguments (8 given)`
Error raises from https://github.com/cocaine/cocaine-tools/blob/master/cocaine/tools/helpers/_unix.py#L37

**Comment by vitalyisaev2** [comment]
Unfortunately, this bug is still reproducible with cocaine-tools installed from PyPi (0.11.6.1), since pip fetches the most recent version of Tornado (4.1) as a dependency.

However, the upstream installation works fine:
```
pip install git+https://github.com/cocaine/cocaine-tools.git@v0.11
```
So I'm afraid that PyPi's cocaine-tool package is outdated.

**Comment by noxiouz** [comment]
Yes, thanks! 
@3Hren, could you please upload the last version (0.11.7.5) of cocaine-tools to PyPi?

**Comment by 3Hren** [comment]
Done.

**Comment by noxiouz** [comment]
Thank you!
