### ISSUE TITLE
Proper support of chunked transfer encoding

### ISSUE THREAD

**Issue by noxiouz** [cocaine/cocaine-tools#23]
If `Transfer-Encoding: chunked` presents, encode body chunks according to
 http://tools.ietf.org/html/rfc7230#section-4.1. Otherwise proxy should treat a response as non-chunked even if `Content-Length` does not present (content length will be calculated after collecting all chunk from an apllication) to support backward compatibility.

**Comment by 3Hren** [comment]
Already landed.
