### ISSUE TITLE
Example of Docker image importing (v 0.11)

### ISSUE THREAD

**Issue by vitalyisaev2** [cocaine/cocaine-tools#24]
Hello!
It seems like [this commit](https://github.com/cocaine/cocaine-tools/commit/45a59ae52acd32c6b6f8ca0da5b07004203b09b9) implements the ability of pulling Docker image from Registry at the time of ```cocaine-tool app upload``` (instead of building them from scratch on Cocaine Runtime server). Unfortunately I wasn't able to find out how to use this feature from docs. Could you please post example of cocaine application launch with the use of external Docker Registry server? Thank you.

**Comment by noxiouz** [comment]
Let's assume your containern named ```myapp``` and it's uploaded to ```otherregistry.host.net:5000```.
The only thing you have to do is to upload manifest for your application to Cocaine storage (to let cocaine know about ypur app):
```bash
cocaine-tool app upload --name myapp --manifest manifets_for_your_app.json --manifest-only
```
The application must be started with a profile, where an isolation type is ```docker```. Please, look to the second comment https://github.com/cocaine/cocaine-plugins/issues/36

**Comment by vitalyisaev2** [comment]
@noxiouz , thank you a lot! Works good, but with several restrictions.

When I try to load the image from the Registry that runs behind HTTPS proxy:
```sh
cocaine-tool app upload --name id-tool_test --manifest app/manifest.dnsdock.json --manifest-only
cocaine-tool start -n id-tool_test -r docker-test
{
    "id-tool_test": "Unable to create an image."
}

```
I get the following error:
```
 [Fri Jul 24 14:41:59 2015] [WARNING] app/id-tool_test: Unable to create an image. Docker replied with body: '{"status":"Pulling repository mailtest-4.dev.search.km/id-tool_test"}
{"errorDetail":{"message":"Authentication is required."},"error":"Authentication is required."}
```

However, when I pull the image manually, I can start the application:
```sh
docker pull mailtest-4.dev.search.km/id-tool_test
...
cocaine-tool start -n id-tool_test -r docker-test
{
    "id-tool_test": "the app has been started"
}
```
Please let me sure that I got this correctly: ```libcocaine-plugin-docker``` can't work with HTTPS Registry (taking into account that local Docker client is successfully authenticated into that Registry).

**Comment by noxiouz** [comment]
```libcocaine-plugin-docker``` doesn't work with registry. It sends requets to a local Docker. Did you do ```docker login``` before pulling the image? Could you show me the profile for your application.

**Comment by vitalyisaev2** [comment]
Yes, I did `docker login` before the application start, after that I got '.dockercfg' file (see below):
```bash
$ cat docker-registry 
{
    "queue-limit": 1000,
    "pool-limit": 10,
    "isolate": {
        "type": "docker",
        "args": {
            "memory_limit": 100000000,
            "endpoint": "unix:///var/run/docker.sock",
            "registry": "mailtest-4.dev.search.km",
            "cpu_shares": 0
        }
    },
    "log-output": true,
    "concurrency": 200
}
$ cat ~/.dockercfg 
{
	"mailtest-4.dev.search.km": {
		"auth": "SOME_HASH_HERE",
		"email": ""
	}
}
```

Alll together again:
```bash
$ cocaine-tool app upload -n id-tool_test2 --manifest app/manifest.dnsdock.json --manifest-only
Setting timeout to the 120.000000s
[  OK  ] Loading manifest
[  OK  ] Uploading manifest
$ cocaine-tool app start -n id-tool_test2 -r docker-registry 
{
    "id-tool_test2": "Unable to create an image."
}
$ docker pull mailtest-4.dev.search.km/id-tool_test2
Pulling repository mailtest-4.dev.search.km/id-tool_test2
f26a3d9aa657: Download complete 
c87d97ed7d49: Download complete 
3ed890b0e33e: Download complete 
e9938c931006: Download complete 
ab57dbafeeea: Download complete 
66f7ddd64696: Download complete 
8e0bd56abc95: Download complete 
985f8a18afe4: Download complete 
4f0db51fe467: Download complete 
242b505f6897: Download complete 
d87d6da7d9d1: Download complete 
6121f0e2586e: Download complete 
bc64481022de: Download complete 
bde80e152ac5: Download complete 
Status: Downloaded newer image for mailtest-4.dev.search.km/id-tool_test2:latest
$ cocaine-tool app start -n id-tool_test2 -r docker-registry
{
    "id-tool_test2": "the app has been started"
}
```

**Comment by noxiouz** [comment]
Yes, the plugin doesn't support authorization for spooling a container. I'll investigate the issue

**Comment by vitalyisaev2** [comment]
I really appreciate it!
