### ISSUE TITLE
Where did `cocaine-tool proxy` command go?

### ISSUE THREAD

**Issue by faucct** [cocaine/cocaine-tools#50]
I have almost succeeded in updating the vagrant example for cocaine 12 compiled from source with the help of this comment (https://github.com/cocaine/cocaine-tools/issues/30#issuecomment-134298560). I am stuck at this step now: `cocaine-tool proxy start --daemon --port=80`. It says that the proxy command is not known to it. I have read the cocaine-tools changelog: it lacks any notes about this change.

**Comment by 3Hren** [comment]
The subcommand was dropped in favor of standalone script. The reason is: single entry point for both attached to terminal and detached (as daemon) use cases.

See here: https://github.com/cocaine/cocaine-tools/blob/master/setup.py#L72
